script:
- set -o pipefail && xcodebuild test -workspace Example/ConcentricProgressRingView.xcworkspace -scheme ConcentricProgressRingView-Example -destination "platform=iOS Simulator,name=iPhone X" | xcpretty
- bundle exec pod lib lint

before_install:
  - gem update --system
  - gem install bundler

language: objective-c
osx_image: xcode9.2
